
import { Culture, Plot } from './types';

export const MONTHS_FR = ['Jan', 'Fév', 'Mar', 'Avr', 'Mai', 'Jui', 'Jul', 'Aoû', 'Sep', 'Oct', 'Nov', 'Déc'];
export const MONTHS_SHORT = ['J', 'F', 'M', 'A', 'M', 'J', 'J', 'A', 'S', 'O', 'N', 'D'];

export const CULTURES: Culture[] = [
  // --- RACINES & TUBERCULES ---
  {
    id: 'pdt',
    name: 'Pommes de Terre',
    category: 'Tubercules',
    varieties: [
      { name: 'Charlotte', description: 'Chair ferme, excellente tenue.', advantage: 'Polyvalente cuisine', waterNeedLevel: 2 },
      { name: 'Bintje', description: 'Chair farineuse, idéale frites.', advantage: 'Gros rendement', yieldBoost: '+15%', waterNeedLevel: 2 },
      { name: 'Ratte du Touquet', description: 'Petit calibre, goût noisette.', advantage: 'Goût gastronomique', waterNeedLevel: 2 },
      { name: 'Vitelotte', description: 'Peau et chair violette.', advantage: 'Originalité & Antioxydants', waterNeedLevel: 2 },
      { name: 'Désirée', description: 'Peau rouge, rustique.', advantage: 'Résiste à la sécheresse', waterNeedLevel: 1 },
      { name: 'Belle de Fontenay', description: 'Très précoce, chair ferme.', advantage: 'Primeur délicate', waterNeedLevel: 2 }
    ],
    description: 'La base de l\'autonomie alimentaire. Se conserve tout l\'hiver en cave.',
    image: 'https://www.themealdb.com/images/ingredients/Potatoes.png',
    exposure: 'Soleil',
    waterNeeds: 'Moyen',
    watering: { frequency: '1x / 10 jours', volumePerPlant: 3 },
    yield: { amount: 3, unit: 'kg/m²', description: 'Env. 800g à 1kg par plant selon variété.' },
    maintenanceTips: 'Le buttage est CRUCIAL : ramenez la terre sur les pieds dès qu\'ils font 15cm pour multiplier les tubercules.',
    growingMethods: 'Culture classique en rangs buttés, ou méthode "sous paille" (Ruth Stout).',
    soilCoverage: 'Associez au Lin (repousse doryphores).',
    associations: ['Haricots', 'Pois', 'Choux', 'Maïs', 'Lin', 'Capucine'],
    plantsPerPerson: 25,
    spacingCm: { betweenPlants: 40, betweenRows: 65 },
    rotations: ['Légumineuses', 'Fruits'],
    diseases: [{ name: 'Mildiou', solution: 'Bouillie bordelaise préventive.' }],
    planning: { sowing: [], planting: [3, 4, 5], maintenance: [4, 5, 6, 7], harvest: [7, 8, 9] }
  },
  {
    id: 'carottes',
    name: 'Carottes',
    category: 'Racines',
    varieties: [
      { name: 'Nantaise', description: 'Demi-longue, cylindrique.', advantage: 'Récolte d\'été sucrée', waterNeedLevel: 2 },
      { name: 'De Colmar', description: 'Cœur rouge, grosse racine.', advantage: 'Conservation hivernale', yieldBoost: '+10%', waterNeedLevel: 2 },
      { name: 'Touchon', description: 'Chair ferme, sans cœur.', advantage: 'Maturité rapide', waterNeedLevel: 2 },
      { name: 'Purple Haze', description: 'Violette dehors, orange dedans.', advantage: 'Décorative', waterNeedLevel: 2 },
      { name: 'Blanche de Kuttingen', description: 'Racine blanche ancienne.', advantage: 'Goût sauvage', waterNeedLevel: 1 }
    ],
    description: 'Légume racine indispensable, riche en vitamines.',
    image: 'https://www.themealdb.com/images/ingredients/Carrots.png',
    exposure: 'Soleil',
    waterNeeds: 'Moyen',
    watering: { frequency: '2x / semaine', volumePerPlant: 0.5 },
    yield: { amount: 2.5, unit: 'kg/m²', description: 'Rendement très dépendant de la qualité du sol.' },
    maintenanceTips: 'L\'éclaircissage est l\'étape la plus importante.',
    growingMethods: 'Semer dans du sable mélangé à du marc de café.',
    soilCoverage: 'Associer avec le Poireau contre la mouche.',
    associations: ['Poireaux', 'Oignons', 'Radis', 'Laitues', 'Ciboulette'],
    plantsPerPerson: 50,
    spacingCm: { betweenPlants: 5, betweenRows: 25 },
    rotations: ['Légumineuses', 'Feuilles'],
    diseases: [{ name: 'Mouche de la carotte', solution: 'Filet anti-insectes ou poireaux.' }],
    planning: { sowing: [3, 4, 5, 6], planting: [], maintenance: [5, 6, 7], harvest: [7, 8, 9, 10, 11] }
  },
  {
    id: 'betteraves',
    name: 'Betteraves',
    category: 'Racines',
    varieties: [
      { name: 'Rouge de Détroit', description: 'Racine globe, chair rouge foncé.', advantage: 'Standard productif', waterNeedLevel: 2 },
      { name: 'Chioggia', description: 'Chair sucrée cerclée de blanc/rose.', advantage: 'Esthétique incroyable', waterNeedLevel: 2 },
      { name: 'Crapaudine', description: 'Peau rugueuse, forme allongée.', advantage: 'Goût authentique ancien', waterNeedLevel: 1 },
      { name: 'Burpee\'s Golden', description: 'Chair jaune d\'or.', advantage: 'Plus douce, ne tache pas', waterNeedLevel: 2 }
    ],
    description: 'Racine sucrée facile à cultiver, se consomme crue ou cuite.',
    image: 'https://www.themealdb.com/images/ingredients/Beetroot.png',
    exposure: 'Soleil',
    waterNeeds: 'Moyen',
    watering: { frequency: '1x / semaine', volumePerPlant: 1 },
    yield: { amount: 3, unit: 'kg/m²', description: 'Grosses racines si bien espacées.' },
    maintenanceTips: 'Les jeunes feuilles se mangent en salade.',
    growingMethods: 'Semis direct ou en godet.',
    soilCoverage: 'Bonne compagne des oignons et laitues.',
    associations: ['Oignons', 'Laitues', 'Choux', 'Haricots'],
    plantsPerPerson: 15,
    spacingCm: { betweenPlants: 15, betweenRows: 30 },
    rotations: ['Légumineuses', 'Fruits'],
    diseases: [{ name: 'Cercosporiose', solution: 'Couper les feuilles tachées.' }],
    planning: { sowing: [3, 4, 5, 6], planting: [], maintenance: [5, 6, 7, 8], harvest: [6, 7, 8, 9, 10] }
  },
  {
    id: 'radis',
    name: 'Radis',
    category: 'Racines',
    varieties: [
      { name: 'De 18 jours', description: 'Petit, long et rose.', advantage: 'Ultra-rapide', waterNeedLevel: 2 },
      { name: 'Rond Écarlate', description: 'Boule rouge classique.', advantage: 'Croquant', waterNeedLevel: 2 },
      { name: 'Glaçon', description: 'Long blanc transparent.', advantage: 'Ne pique pas', waterNeedLevel: 2 },
      { name: 'Noir Long d\'Hiver', description: 'Peau noire, chair blanche.', advantage: 'Conservation hivernale', waterNeedLevel: 1 },
      { name: 'National', description: 'Rond rouge à bout blanc.', advantage: 'Classique', waterNeedLevel: 2 }
    ],
    description: 'Le légume "bouche-trou" idéal.',
    image: 'https://www.themealdb.com/images/ingredients/Radish.png',
    exposure: 'Mi-ombre',
    waterNeeds: 'Moyen',
    watering: { frequency: 'Tous les 2 jours', volumePerPlant: 0.1 },
    yield: { amount: 1, unit: 'kg/m²', description: 'Culture rapide.' },
    maintenanceTips: 'Arrosage fréquent pour éviter le piquant.',
    growingMethods: 'Semis à la volée ou en ligne.',
    soilCoverage: 'Rapide.',
    associations: ['Carottes', 'Laitues', 'Pois'],
    plantsPerPerson: 40,
    spacingCm: { betweenPlants: 3, betweenRows: 15 },
    rotations: ['Légumineuses', 'Feuilles'],
    diseases: [{ name: 'Altises', solution: 'Maintenir humide.' }],
    planning: { sowing: [3, 4, 5, 6, 7, 8, 9], planting: [], maintenance: [4, 5, 6, 7, 8, 9, 10], harvest: [4, 5, 6, 7, 8, 9, 10] }
  },
  {
    id: 'panais',
    name: 'Panais',
    category: 'Racines',
    varieties: [
        { name: 'Demi-long de Guernesey', description: 'Racine blanche charnue.', advantage: 'Très rustique', waterNeedLevel: 2 },
        { name: 'Tender and True', description: 'Longue racine régulière.', advantage: 'Saveur douce', waterNeedLevel: 2 }
    ],
    description: 'Cousin de la carotte au goût de noisette, résiste au gel.',
    image: 'https://www.themealdb.com/images/ingredients/Parsnip.png',
    exposure: 'Soleil',
    waterNeeds: 'Moyen',
    watering: { frequency: '1x / semaine', volumePerPlant: 1 },
    yield: { amount: 2.5, unit: 'kg/m²', description: 'Se récolte tout l\'hiver.' },
    maintenanceTips: 'Le froid bonifie son goût (le rend plus sucré).',
    growingMethods: 'Semis direct obligatoire (racine pivot).',
    soilCoverage: 'Feuillage dense.',
    associations: ['Oignons', 'Poireaux'],
    plantsPerPerson: 15,
    spacingCm: { betweenPlants: 15, betweenRows: 35 },
    rotations: ['Légumineuses'],
    diseases: [],
    planning: { sowing: [3, 4, 5, 6], planting: [], maintenance: [6, 7, 8], harvest: [10, 11, 12, 1, 2] }
  },

  // --- FRUITS & CUCURBITACÉES ---
  {
    id: 'tomates',
    name: 'Tomates',
    category: 'Fruits',
    varieties: [
      { name: 'Cœur de Bœuf', description: 'Gros fruit charnu, peu de graines.', advantage: 'Reine des salades', waterNeedLevel: 3 },
      { name: 'Noire de Crimée', description: 'Fruit sombre, goût fumé/sucré.', advantage: 'Saveur exceptionnelle', waterNeedLevel: 3 },
      { name: 'Roma', description: 'Allongée, chair ferme.', advantage: 'Idéale pour les sauces', yieldBoost: '+20%', waterNeedLevel: 2 },
      { name: 'Ananas', description: 'Grosse, jaune et rouge.', advantage: 'Chair dense sans acidité', waterNeedLevel: 3 },
      { name: 'Green Zebra', description: 'Verte zébrée, petit calibre.', advantage: 'Acidulée et décorative', waterNeedLevel: 2 },
      { name: 'Saint-Pierre', description: 'Ronde, rouge classique.', advantage: 'Rustique et productive', waterNeedLevel: 2 },
      { name: 'Marmande', description: 'Côtelée et précoce.', advantage: 'Hâtive', waterNeedLevel: 2 },
      { name: 'Cerise', description: 'Petits fruits en grappe.', advantage: 'Productivité & Apéro', yieldBoost: '+50% (nombre)', waterNeedLevel: 2 }
    ],
    description: 'La star du potager. Exigeante mais tellement gratifiante.',
    image: 'https://www.themealdb.com/images/ingredients/Tomato.png',
    exposure: 'Soleil',
    waterNeeds: 'Élevé',
    watering: { frequency: '2x / semaine', volumePerPlant: 4 },
    yield: { amount: 3, unit: 'kg/plant', description: 'Peut monter à 5-6kg sur de la tomate cerise.' },
    maintenanceTips: 'Supprimez les gourmands. Ne mouillez jamais le feuillage.',
    growingMethods: 'Planter en enterrant la tige profondément.',
    soilCoverage: 'Basilic au pied.',
    associations: ['Basilic', 'Œillet d\'Inde', 'Carottes', 'Poireaux', 'Ail'],
    plantsPerPerson: 6,
    spacingCm: { betweenPlants: 60, betweenRows: 80 },
    rotations: ['Racines', 'Feuilles', 'Légumineuses'],
    diseases: [{ name: 'Mildiou', solution: 'Protéger de la pluie (toit).' }],
    planning: { sowing: [2, 3], planting: [5, 6], maintenance: [6, 7, 8], harvest: [7, 8, 9, 10] }
  },
  {
    id: 'courgettes',
    name: 'Courgettes',
    category: 'Fruits',
    varieties: [
      { name: 'Noire Maraîchère', description: 'Verte foncé, cylindrique.', advantage: 'Le grand classique', waterNeedLevel: 3 },
      { name: 'Gold Rush', description: 'Fruit jaune vif.', advantage: 'Ne se cache pas sous les feuilles', waterNeedLevel: 3 },
      { name: 'Ronde de Nice', description: 'Petit fruit rond.', advantage: 'Parfait pour farcir', waterNeedLevel: 3 },
      { name: 'Grisette de Provence', description: 'Vert clair, goût fin.', advantage: 'Très tendre', waterNeedLevel: 3 },
      { name: 'Patisson', description: 'Forme de soucoupe volante.', advantage: 'Goût d\'artichaut', waterNeedLevel: 2 }
    ],
    description: 'Productivité record. 2-3 pieds suffisent souvent pour une famille.',
    image: 'https://www.themealdb.com/images/ingredients/Zucchini.png',
    exposure: 'Soleil',
    waterNeeds: 'Élevé',
    watering: { frequency: '3x / semaine', volumePerPlant: 5 },
    yield: { amount: 10, unit: 'kg/plant', description: 'Une courgette tous les 2-3 jours.' },
    maintenanceTips: 'Récoltez jeune (20cm) pour stimuler la production.',
    growingMethods: 'Adore le compost frais.',
    soilCoverage: 'Ses grandes feuilles couvrent le sol.',
    associations: ['Maïs', 'Haricots', 'Capucines', 'Menthe'],
    plantsPerPerson: 2,
    spacingCm: { betweenPlants: 100, betweenRows: 100 },
    rotations: ['Racines', 'Légumineuses'],
    diseases: [{ name: 'Oïdium (blanc)', solution: 'Lait dilué (10%) ou soufre.' }],
    planning: { sowing: [4, 5], planting: [5, 6], maintenance: [6, 7, 8], harvest: [7, 8, 9] }
  },
  {
    id: 'poivrons',
    name: 'Poivrons & Piments',
    category: 'Fruits',
    varieties: [
        { name: 'Yolo Wonder', description: 'Gros poivron carré rouge.', advantage: 'Chair épaisse douce', waterNeedLevel: 3 },
        { name: 'California Wonder', description: 'Carré, vert puis rouge.', advantage: 'Reference productive', waterNeedLevel: 3 },
        { name: 'Doux des Landes', description: 'Très long et fin.', advantage: 'Frit ou salade', waterNeedLevel: 2 },
        { name: 'Corno di Toro', description: 'Allongé comme une corne.', advantage: 'Très parfumé', waterNeedLevel: 2 },
        { name: 'Espelette', description: 'Piment basque AOP.', advantage: 'Piquant modéré (4/10)', waterNeedLevel: 2 }
    ],
    description: 'Demande beaucoup de chaleur et de temps pour mûrir.',
    image: 'https://www.themealdb.com/images/ingredients/Red%20Pepper.png',
    exposure: 'Soleil',
    waterNeeds: 'Élevé',
    watering: { frequency: '2x / semaine', volumePerPlant: 3 },
    yield: { amount: 1.5, unit: 'kg/plant', description: '8 à 12 fruits par pied.' },
    maintenanceTips: 'Enlever la première fleur centrale pour fortifier le pied.',
    growingMethods: 'Paillage foncé pour garder la chaleur.',
    soilCoverage: 'Faible.',
    associations: ['Tomates', 'Aubergines', 'Basilic'],
    plantsPerPerson: 4,
    spacingCm: { betweenPlants: 50, betweenRows: 60 },
    rotations: ['Racines'],
    diseases: [],
    planning: { sowing: [2, 3], planting: [5, 6], maintenance: [6, 7, 8], harvest: [8, 9, 10] }
  },
  {
    id: 'aubergines',
    name: 'Aubergines',
    category: 'Fruits',
    varieties: [
      { name: 'Black Beauty', description: 'Gros fruit violet noir.', advantage: 'La référence', waterNeedLevel: 3 },
      { name: 'De Barbentane', description: 'Allongée, violette.', advantage: 'Précoce et productive', waterNeedLevel: 3 },
      { name: 'Dourga', description: 'Blanche, forme d\'œuf.', advantage: 'Chair douce, peau fine', waterNeedLevel: 3 },
      { name: 'Violette de Florence', description: 'Grosse, ronde et côtelée.', advantage: 'Chair dense', waterNeedLevel: 3 }
    ],
    description: 'Légume du soleil par excellence. Croissance lente.',
    image: 'https://www.themealdb.com/images/ingredients/Eggplant.png',
    exposure: 'Soleil',
    waterNeeds: 'Élevé',
    watering: { frequency: '2x / semaine', volumePerPlant: 4 },
    yield: { amount: 6, unit: 'fruits/plant', description: 'Env. 2 à 3 kg par pied bien nourri.' },
    maintenanceTips: 'Tuteurez solide, les fruits sont lourds.',
    growingMethods: 'Exigeante en chaleur. Paillis foncé recommandé.',
    soilCoverage: 'Moyen.',
    associations: ['Haricots', 'Pois', 'Thym', 'Estragon', 'Souci'],
    plantsPerPerson: 3,
    spacingCm: { betweenPlants: 50, betweenRows: 60 },
    rotations: ['Racines', 'Feuilles'],
    diseases: [{ name: 'Doryphores', solution: 'Ramassage manuel impératif.' }],
    planning: { sowing: [2, 3], planting: [5, 6], maintenance: [6, 7, 8], harvest: [8, 9, 10] }
  },
  {
    id: 'concombres',
    name: 'Concombres',
    category: 'Fruits',
    varieties: [
      { name: 'Marketer', description: 'Long, lisse, vert foncé.', advantage: 'Productif et droit', waterNeedLevel: 3 },
      { name: 'Le Généreux', description: 'Rustique de pleine terre.', advantage: 'Résiste bien', waterNeedLevel: 2 },
      { name: 'Long de Chine', description: 'Très long, fin et courbé.', advantage: 'Croquant, digeste', waterNeedLevel: 3 },
      { name: 'Lemon', description: 'Rond et jaune.', advantage: 'Original et digeste', waterNeedLevel: 2 }
    ],
    description: 'Grimpeur vigoureux, parfait sur un grillage.',
    image: 'https://www.themealdb.com/images/ingredients/Cucumber.png',
    exposure: 'Soleil',
    waterNeeds: 'Élevé',
    watering: { frequency: '3x / semaine', volumePerPlant: 2 },
    yield: { amount: 8, unit: 'fruits/plant', description: 'Récolte régulière tout l\'été.' },
    maintenanceTips: 'Pincez après la 3ème feuille. Arrosez au pied.',
    growingMethods: 'Faites-les grimper sur treillis.',
    soilCoverage: 'Faible si grimpant, fort si rampant.',
    associations: ['Maïs', 'Haricots', 'Laitues', 'Aneth', 'Oignons'],
    plantsPerPerson: 2,
    spacingCm: { betweenPlants: 60, betweenRows: 80 },
    rotations: ['Racines', 'Légumineuses'],
    diseases: [{ name: 'Oïdium', solution: 'Lait, bicarbonate.' }],
    planning: { sowing: [4, 5], planting: [5, 6], maintenance: [6, 7, 8], harvest: [7, 8, 9] }
  },
  {
    id: 'potirons',
    name: 'Potirons & Courges',
    category: 'Fruits',
    varieties: [
      { name: 'Potimarron Red Kuri', description: 'Goût châtaigne, peau comestible.', advantage: 'Le top du goût', waterNeedLevel: 2 },
      { name: 'Butternut', description: 'Chair fine, forme de poire.', advantage: 'Excellente conservation', waterNeedLevel: 2 },
      { name: 'Musquée de Provence', description: 'Énorme citrouille côtelée.', advantage: 'Rendement massif', yieldBoost: '+300%', waterNeedLevel: 3 },
      { name: 'Spaghetti', description: 'Chair filamenteuse.', advantage: 'Original', waterNeedLevel: 2 }
    ],
    description: 'Coureuse envahissante indispensable pour l\'hiver.',
    image: 'https://www.themealdb.com/images/ingredients/Pumpkin.png',
    exposure: 'Soleil',
    waterNeeds: 'Moyen',
    watering: { frequency: '1x / semaine', volumePerPlant: 5 },
    yield: { amount: 3, unit: 'fruits/plant', description: 'Gros fruits de conservation.' },
    maintenanceTips: 'Mettez une tuile sous les fruits.',
    growingMethods: 'Directement sur le tas de compost !',
    soilCoverage: 'Étouffe toutes les mauvaises herbes.',
    associations: ['Maïs', 'Haricots'],
    plantsPerPerson: 1,
    spacingCm: { betweenPlants: 120, betweenRows: 150 },
    rotations: ['Légumineuses'],
    diseases: [{ name: 'Oïdium', solution: 'Inévitable en fin de saison.' }],
    planning: { sowing: [4, 5], planting: [5], maintenance: [6, 7, 8, 9], harvest: [9, 10, 11] }
  },
  {
    id: 'mais',
    name: 'Maïs Doux',
    category: 'Céréales',
    varieties: [
        { name: 'Golden Bantam', description: 'grains jaunes sucrés.', advantage: 'Variété ancienne', waterNeedLevel: 3 },
        { name: 'Popcorn', description: 'Pour éclater.', advantage: 'Conservation sec', waterNeedLevel: 2 }
    ],
    description: 'Idéal pour créer de l\'ombre ou servir de tuteur.',
    image: 'https://www.themealdb.com/images/ingredients/Corn.png',
    exposure: 'Soleil',
    waterNeeds: 'Élevé',
    watering: { frequency: '2x / semaine', volumePerPlant: 2 },
    yield: { amount: 2, unit: 'épis/plant', description: 'Récolte groupée.' },
    maintenanceTips: 'Butter les pieds pour l\'ancrage.',
    growingMethods: 'En bloc (carré) pour une bonne pollinisation par le vent.',
    soilCoverage: 'Hauteur importante.',
    associations: ['Courges', 'Haricots', 'Concombres'],
    plantsPerPerson: 10,
    spacingCm: { betweenPlants: 30, betweenRows: 70 },
    rotations: ['Légumineuses'],
    diseases: [],
    planning: { sowing: [4, 5], planting: [5, 6], maintenance: [6, 7, 8], harvest: [8, 9, 10] }
  },

  // --- FEUILLES ---
  {
    id: 'poireaux',
    name: 'Poireaux',
    category: 'Feuilles',
    varieties: [
      { name: 'Bleu de Solaise', description: 'Feuillage bleuté, très rustique.', advantage: 'Résiste au grand froid', waterNeedLevel: 2 },
      { name: 'Gros Jaune du Poitou', description: 'Gros fût, moins résistant au froid.', advantage: 'Enorme rendement', yieldBoost: '+20%', waterNeedLevel: 2 },
      { name: 'Monstrueux de Carentan', description: 'Fût court et trapu.', advantage: 'Tendre et savoureux', waterNeedLevel: 2 }
    ],
    description: 'Le pilier du potager d\'hiver.',
    image: 'https://www.themealdb.com/images/ingredients/Leek.png',
    exposure: 'Soleil',
    waterNeeds: 'Moyen',
    watering: { frequency: '1x / semaine', volumePerPlant: 1.5 },
    yield: { amount: 3, unit: 'kg/m²', description: 'Env. 150-200g par fût nettoyé.' },
    maintenanceTips: 'Buttez régulièrement pour avoir beaucoup de blanc.',
    growingMethods: 'Repiquage profond dans un sillon.',
    soilCoverage: 'Faible.',
    associations: ['Carottes', 'Fraises', 'Céleri', 'Tomates', 'Oignons'],
    plantsPerPerson: 30,
    spacingCm: { betweenPlants: 15, betweenRows: 35 },
    rotations: ['Légumineuses', 'Racines'],
    diseases: [{ name: 'Teigne (Ver)', solution: 'Voile anti-insecte P17.' }],
    planning: { sowing: [2, 3, 4, 5], planting: [5, 6, 7], maintenance: [8, 9, 10], harvest: [10, 11, 12, 1, 2, 3] }
  },
  {
    id: 'salades',
    name: 'Laitues & Salades',
    category: 'Feuilles',
    varieties: [
      { name: 'Merveille des 4 saisons', description: 'Tête teintée de rouge.', advantage: 'Résiste à la chaleur et au froid', waterNeedLevel: 2 },
      { name: 'Batavia', description: 'Feuilles croquantes et découpées.', advantage: 'Ne monte pas vite en graine', waterNeedLevel: 2 },
      { name: 'Feuille de Chêne', description: 'À couper.', advantage: 'Repousse après coupe', yieldBoost: 'Continue', waterNeedLevel: 2 },
      { name: 'Romaine', description: 'Haut, croquant.', advantage: 'Cæsar salad', waterNeedLevel: 2 }
    ],
    description: 'Culture rapide et facile toute l\'année.',
    image: 'https://www.themealdb.com/images/ingredients/Lettuce.png',
    exposure: 'Mi-ombre',
    waterNeeds: 'Moyen',
    watering: { frequency: 'Tous les 2 jours', volumePerPlant: 0.5 },
    yield: { amount: 0.3, unit: 'kg/plant', description: 'Une salade / semaine / personne.' },
    maintenanceTips: 'Attention aux limaces !',
    growingMethods: 'Semez peu mais SOUVENT.',
    soilCoverage: 'Couvre bien le sol.',
    associations: ['Radis', 'Pois', 'Concombres', 'Carottes', 'Choux'],
    plantsPerPerson: 12,
    spacingCm: { betweenPlants: 25, betweenRows: 30 },
    rotations: ['Racines', 'Fruits'],
    diseases: [{ name: 'Limaces', solution: 'Cendre, coquilles œufs, Ferramol.' }],
    planning: { sowing: [2, 3, 4, 5, 6, 7, 8], planting: [3, 4, 5, 6, 7, 8, 9], maintenance: [4, 5, 6, 7, 8, 9], harvest: [4, 5, 6, 7, 8, 9, 10] }
  },
  {
    id: 'epinards',
    name: 'Épinards',
    category: 'Feuilles',
    varieties: [
      { name: 'Géant d\'Hiver', description: 'Grandes feuilles larges.', advantage: 'Très rustique', waterNeedLevel: 2 },
      { name: 'Matador', description: 'Feuilles foncées charnues.', advantage: 'Lent à monter en graines', waterNeedLevel: 2 },
      { name: 'Monstrueux de Viroflay', description: 'Enormes feuilles.', advantage: 'Vigoureux', waterNeedLevel: 2 }
    ],
    description: 'Riche en fer, aime la fraîcheur.',
    image: 'https://www.themealdb.com/images/ingredients/Spinach.png',
    exposure: 'Mi-ombre',
    waterNeeds: 'Moyen',
    watering: { frequency: '2x / semaine', volumePerPlant: 0.5 },
    yield: { amount: 1.5, unit: 'kg/m²', description: 'Coupez les feuilles extérieures, le cœur repousse.' },
    maintenanceTips: 'Ombrez-les en été.',
    growingMethods: 'Semis direct.',
    soilCoverage: 'Bon engrais vert.',
    associations: ['Fraises', 'Choux', 'Haricots', 'Pois'],
    plantsPerPerson: 20,
    spacingCm: { betweenPlants: 10, betweenRows: 25 },
    rotations: ['Racines', 'Fruits'],
    diseases: [{ name: 'Mildiou', solution: 'Espacer les plants.' }],
    planning: { sowing: [2, 3, 8, 9], planting: [], maintenance: [3, 4, 9, 10], harvest: [4, 5, 10, 11] }
  },
  {
    id: 'choux',
    name: 'Choux',
    category: 'Feuilles',
    varieties: [
        { name: 'Cabus (Pommé)', description: 'Tête lisse et ferme.', advantage: 'Conservation', waterNeedLevel: 2 },
        { name: 'Kale', description: 'Feuilles frisées non pommées.', advantage: 'Superaliment continu', waterNeedLevel: 2 },
        { name: 'Brocoli', description: 'Inflorescences vertes.', advantage: 'Cycle court', waterNeedLevel: 3 },
        { name: 'Chou-Fleur', description: 'Pomme blanche compacte.', advantage: 'Délicat mais délicieux', waterNeedLevel: 3 },
        { name: 'De Bruxelles', description: 'Petites pommes sur tige.', advantage: 'Récolte d\'hiver', waterNeedLevel: 2 },
        { name: 'Romanesco', description: 'Pyramidal vert clair.', advantage: 'Géométrie et douceur', waterNeedLevel: 3 },
        { name: 'Pe-Tsai (Chinois)', description: 'Allongé, type salade.', advantage: 'Croquant', waterNeedLevel: 2 }
    ],
    description: 'Famille très vaste pour récoltes d\'automne et hiver.',
    image: 'https://www.themealdb.com/images/ingredients/Cabbage.png',
    exposure: 'Soleil',
    waterNeeds: 'Moyen',
    watering: { frequency: '1x / semaine', volumePerPlant: 2 },
    yield: { amount: 4, unit: 'kg/m²', description: 'Gros volume alimentaire.' },
    maintenanceTips: 'Pailler impérativement pour garder l\'humidité.',
    growingMethods: 'Plantation profonde.',
    soilCoverage: 'Large.',
    associations: ['Céleri', 'Betteraves', 'Haricots', 'Aromatiques'],
    plantsPerPerson: 10,
    spacingCm: { betweenPlants: 50, betweenRows: 60 },
    rotations: ['Légumineuses'],
    diseases: [{ name: 'Piéride', solution: 'Filet anti-insectes.' }],
    planning: { sowing: [3, 4, 5], planting: [5, 6, 7], maintenance: [7, 8, 9, 10], harvest: [9, 10, 11, 12, 1] }
  },

  // --- LÉGUMINEUSES ---
  {
    id: 'haricots',
    name: 'Haricots',
    category: 'Légumineuses',
    varieties: [
      { name: 'Contender', description: 'Nain, gousse charnue.', advantage: 'Très précoce et productif', waterNeedLevel: 2 },
      { name: 'Coco de Paimpol', description: 'À écosser (grains).', advantage: 'Se congèle ou se sèche', waterNeedLevel: 2 },
      { name: 'Fortex', description: 'À rames (grimpant).', advantage: 'Gousses très longues (25cm)', yieldBoost: '+50%', waterNeedLevel: 2 },
      { name: 'Beurre de Rocquencourt', description: 'Jaune doré, fin.', advantage: 'Goût fin, productif', waterNeedLevel: 2 },
      { name: 'Merveille de Venise', description: 'Plat jaune, grimpant.', advantage: 'Beurre à rames', waterNeedLevel: 2 },
      { name: 'Delinel', description: 'Vert fin sans fil.', advantage: 'Résistant', waterNeedLevel: 2 }
    ],
    description: 'Enrichit le sol en azote. Délicieux frais ou sec.',
    image: 'https://www.themealdb.com/images/ingredients/Green%20Beans.png',
    exposure: 'Soleil',
    waterNeeds: 'Moyen',
    watering: { frequency: '1x / semaine', volumePerPlant: 1 },
    yield: { amount: 1.5, unit: 'kg/m²', description: 'Plus productif en variétés à rames.' },
    maintenanceTips: 'Récoltez tous les 2 jours.',
    growingMethods: 'Semis en "poquets".',
    soilCoverage: 'Régénère le sol.',
    associations: ['Pommes de Terre', 'Carottes', 'Choux', 'Courges', 'Sarriette', 'Fraises'],
    plantsPerPerson: 20,
    spacingCm: { betweenPlants: 10, betweenRows: 40 },
    rotations: ['Feuilles', 'Racines', 'Fruits'],
    diseases: [{ name: 'Anthracnose', solution: 'Rotation.' }],
    planning: { sowing: [5, 6, 7], planting: [], maintenance: [6, 7, 8], harvest: [7, 8, 9] }
  },
  {
    id: 'pois',
    name: 'Petits Pois',
    category: 'Légumineuses',
    varieties: [
      { name: 'Petit Provençal', description: 'Nain, grains ronds.', advantage: 'Hâtif pour le printemps', waterNeedLevel: 2 },
      { name: 'Merveille de Kelvedon', description: 'Nain, grains ridés.', advantage: 'Très sucré', waterNeedLevel: 2 },
      { name: 'Mangetout', description: 'Se mange avec la cosse.', advantage: 'Pas d\'écossage !', waterNeedLevel: 2 }
    ],
    description: 'Sucre naturel exceptionnel.',
    image: 'https://www.themealdb.com/images/ingredients/Peas.png',
    exposure: 'Mi-ombre',
    waterNeeds: 'Moyen',
    watering: { frequency: '1x / semaine', volumePerPlant: 1 },
    yield: { amount: 0.8, unit: 'kg/m²', description: 'Env. 400g par pied pour les rames.' },
    maintenanceTips: 'Installez rames ou grillage.',
    growingMethods: 'Culture de temps frais.',
    soilCoverage: 'Fixe l\'azote.',
    associations: ['Carottes', 'Navets', 'Radis', 'Pommes de Terre', 'Céleri'],
    plantsPerPerson: 25,
    spacingCm: { betweenPlants: 5, betweenRows: 50 },
    rotations: ['Feuilles', 'Racines'],
    diseases: [{ name: 'Oïdium', solution: 'Éviter arrosage feuillage.' }],
    planning: { sowing: [2, 3, 4, 10, 11], planting: [], maintenance: [3, 4, 5], harvest: [5, 6] }
  },
  {
    id: 'feves',
    name: 'Fèves',
    category: 'Légumineuses',
    varieties: [
        { name: 'D\'Aguadulce', description: 'Très longues cosses.', advantage: 'Semis d\'automne possible (Sud)', waterNeedLevel: 2 },
        { name: 'De Séville', description: 'Gros grains.', advantage: 'Vigoureuse', waterNeedLevel: 2 }
    ],
    description: 'Première récolte de l\'année au potager.',
    image: 'https://www.themealdb.com/images/ingredients/Broad%20Beans.png',
    exposure: 'Soleil',
    waterNeeds: 'Faible',
    watering: { frequency: '1x / 2 semaines', volumePerPlant: 1 },
    yield: { amount: 1, unit: 'kg/m²', description: 'Nourrissant.' },
    maintenanceTips: 'Pincer la tête quand la plante a 6 étages de fleurs (contre pucerons).',
    growingMethods: 'Semis direct.',
    soilCoverage: 'Engrais vert puissant.',
    associations: ['Laitues', 'Artichauts'],
    plantsPerPerson: 10,
    spacingCm: { betweenPlants: 15, betweenRows: 40 },
    rotations: ['Feuilles'],
    diseases: [{ name: 'Pucerons noirs', solution: 'Savon noir ou pincer les têtes.' }],
    planning: { sowing: [2, 3, 10, 11], planting: [], maintenance: [3, 4, 5], harvest: [5, 6] }
  },

  // --- BULBES ---
  {
    id: 'oignons',
    name: 'Oignons & Ail',
    category: 'Bulbes',
    varieties: [
      { name: 'Jaune Paille', description: 'Oignon de garde classique.', advantage: 'Conservation > 6 mois', waterNeedLevel: 1 },
      { name: 'Rouge de Brunswick', description: 'Oignon rouge doux.', advantage: 'Délicieux cru', waterNeedLevel: 1 },
      { name: 'Ail Violet', description: 'Têtes parfumées.', advantage: 'Indispensable', waterNeedLevel: 1 },
      { name: 'Échalote Grise', description: 'Goût très fin.', advantage: 'La préférée des chefs', waterNeedLevel: 1 }
    ],
    description: 'Indispensables en cuisine, conservation longue durée.',
    image: 'https://www.themealdb.com/images/ingredients/Onion.png',
    exposure: 'Soleil',
    waterNeeds: 'Faible',
    watering: { frequency: '1x / 2 semaines', volumePerPlant: 0.5 },
    yield: { amount: 2, unit: 'kg/m²', description: 'Env. 5 à 8 oignons au mètre linéaire.' },
    maintenanceTips: 'Ne jamais arroser en fin de cycle.',
    growingMethods: 'Planter sur butte (billon).',
    soilCoverage: 'Faible.',
    associations: ['Carottes', 'Tomates', 'Fraises', 'Laitues'],
    plantsPerPerson: 40,
    spacingCm: { betweenPlants: 10, betweenRows: 25 },
    rotations: ['Fruits', 'Légumineuses'],
    diseases: [{ name: 'Pourriture', solution: 'Sol drainé impératif.' }],
    planning: { sowing: [2, 3], planting: [3, 4, 10, 11], maintenance: [5, 6], harvest: [7, 8] }
  },

  // --- AROMATIQUES ---
  {
    id: 'basilic',
    name: 'Basilic',
    category: 'Aromatiques',
    varieties: [
      { name: 'Grand Vert', description: 'Grandes feuilles bombées.', advantage: 'Le classique pesto', waterNeedLevel: 2 },
      { name: 'Fin Vert', description: 'Petites feuilles.', advantage: 'Esthétique en boule', waterNeedLevel: 2 },
      { name: 'Pourpre', description: 'Feuilles violettes.', advantage: 'Décoratif et poivré', waterNeedLevel: 2 }
    ],
    description: 'Le compagnon inséparable de la tomate.',
    image: 'https://www.themealdb.com/images/ingredients/Basil.png',
    exposure: 'Soleil',
    waterNeeds: 'Moyen',
    watering: { frequency: '2x / semaine', volumePerPlant: 0.3 },
    yield: { amount: 0.2, unit: 'kg/plant', description: 'Récolte continue.' },
    maintenanceTips: 'Pincez les têtes dès l\'apparition des fleurs.',
    growingMethods: 'Craint le soleil brûlant de midi.',
    soilCoverage: 'Odeur répulsive.',
    associations: ['Tomates', 'Poivrons', 'Aubergines', 'Courgettes'],
    plantsPerPerson: 4,
    spacingCm: { betweenPlants: 25, betweenRows: 30 },
    rotations: ['Tubercules', 'Légumineuses'],
    diseases: [{ name: 'Fusariose', solution: 'Rotation.' }],
    planning: { sowing: [3, 4], planting: [5, 6], maintenance: [6, 7, 8, 9], harvest: [6, 7, 8, 9, 10] }
  },
  {
    id: 'menthe',
    name: 'Menthe',
    category: 'Aromatiques',
    varieties: [
      { name: 'Verte', description: 'Classique thé/mojito.', advantage: 'Indestructible', waterNeedLevel: 3 },
      { name: 'Poivrée', description: 'Goût très fort mentholé.', advantage: 'Médicinale', waterNeedLevel: 3 },
      { name: 'Chocolat', description: 'Tiges foncées, arrière-goût cacao.', advantage: 'Surprenante', waterNeedLevel: 3 }
    ],
    description: 'Envahissante mais délicieuse.',
    image: 'https://www.themealdb.com/images/ingredients/Mint.png',
    exposure: 'Mi-ombre',
    waterNeeds: 'Élevé',
    watering: { frequency: '3x / semaine', volumePerPlant: 0.5 },
    yield: { amount: 0.5, unit: 'kg/plant', description: 'Plus on coupe, plus elle pousse.' },
    maintenanceTips: 'Coupez ras à l\'automne.',
    growingMethods: 'En pot ou zone dédiée isolée.',
    soilCoverage: 'Très dense.',
    associations: ['Choux', 'Tomates'],
    plantsPerPerson: 1,
    spacingCm: { betweenPlants: 40, betweenRows: 40 },
    rotations: ['Aromatiques'],
    diseases: [{ name: 'Rouille', solution: 'Couper tout.' }],
    planning: { sowing: [3, 4], planting: [3, 4, 5], maintenance: [5, 6, 7, 8], harvest: [5, 6, 7, 8, 9, 10] }
  },
  {
    id: 'thym',
    name: 'Thym',
    category: 'Aromatiques',
    varieties: [
        { name: 'Commun', description: 'Le thym de garrigue.', advantage: 'Très parfumé', waterNeedLevel: 1 },
        { name: 'Citron', description: 'Feuillage panaché jaune.', advantage: 'Parfum citronné unique', waterNeedLevel: 1 }
    ],
    description: 'Vivace de garrigue.',
    image: 'https://www.themealdb.com/images/ingredients/Thyme.png',
    exposure: 'Soleil',
    waterNeeds: 'Faible',
    watering: { frequency: '1x / mois', volumePerPlant: 0.2 },
    yield: { amount: 0.2, unit: 'kg/plant', description: 'Toute l\'année.' },
    maintenanceTips: 'Taillez après floraison.',
    growingMethods: 'Sol pauvre et sec.',
    soilCoverage: 'Nul.',
    associations: ['Choux', 'Fraises'],
    plantsPerPerson: 1,
    spacingCm: { betweenPlants: 30, betweenRows: 30 },
    rotations: ['Aromatiques'],
    diseases: [],
    planning: { sowing: [4, 5], planting: [3, 4, 9, 10], maintenance: [6], harvest: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12] }
  },
  {
    id: 'romarin',
    name: 'Romarin',
    category: 'Aromatiques',
    varieties: [
        { name: 'Officinal', description: 'Arbuste dressé.', advantage: 'Classique', waterNeedLevel: 1 },
        { name: 'Rampant', description: 'Couvre-sol.', advantage: 'Décoratif sur muret', waterNeedLevel: 1 }
    ],
    description: 'Arbuste persistant.',
    image: 'https://www.themealdb.com/images/ingredients/Rosemary.png',
    exposure: 'Soleil',
    waterNeeds: 'Faible',
    watering: { frequency: 'Jamais après reprise', volumePerPlant: 0 },
    yield: { amount: 0.5, unit: 'kg/plant', description: 'Annuel.' },
    maintenanceTips: 'Taille légère.',
    growingMethods: 'Sol drainé.',
    soilCoverage: 'Arbuste.',
    associations: ['Carottes', 'Choux'],
    plantsPerPerson: 1,
    spacingCm: { betweenPlants: 80, betweenRows: 80 },
    rotations: ['Aromatiques'],
    diseases: [],
    planning: { sowing: [], planting: [3, 4, 9, 10], maintenance: [], harvest: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12] }
  },

  // --- PETITS FRUITS ---
  {
    id: 'fraises',
    name: 'Fraises',
    category: 'Petits Fruits',
    varieties: [
      { name: 'Gariguette', description: 'Allongée, précoce (mai).', advantage: 'Premier fruit du printemps', waterNeedLevel: 2 },
      { name: 'Mara des Bois', description: 'Goût fraise des bois.', advantage: 'Remontante (produit 2 fois)', yieldBoost: '+30% (durée)', waterNeedLevel: 2 },
      { name: 'Charlotte', description: 'Grosse et sucrée.', advantage: 'Très productive', waterNeedLevel: 2 }
    ],
    description: 'Vivace gourmande.',
    image: 'https://www.themealdb.com/images/ingredients/Strawberries.png',
    exposure: 'Soleil',
    waterNeeds: 'Moyen',
    watering: { frequency: '2x / semaine', volumePerPlant: 0.5 },
    yield: { amount: 0.5, unit: 'kg/plant', description: 'Jusqu\'à 800g.' },
    maintenanceTips: 'Coupez les stolons.',
    growingMethods: 'Sur toile ou paillage.',
    soilCoverage: 'Bonne couverture.',
    associations: ['Poireaux', 'Oignons', 'Ail', 'Épinards', 'Bourrache', 'Laitues'],
    plantsPerPerson: 15,
    spacingCm: { betweenPlants: 30, betweenRows: 40 },
    rotations: ['Légumineuses', 'Feuilles'],
    diseases: [{ name: 'Pourriture grise', solution: 'Paillage.' }],
    planning: { sowing: [], planting: [3, 4, 8, 9], maintenance: [4, 5, 6, 7], harvest: [5, 6, 7, 8, 9] }
  },
];

export const INITIAL_PLOTS: Plot[] = [
  { id: '1', name: 'Planche Principale', type: 'culture', shape: 'rect', x: 2, y: 2, width: 5, height: 1.2, rotation: 0, opacity: 1, exposure: 'Soleil', plantedCultureId: 'tomates', selectedVariety: 'Cœur de Bœuf' },
  { id: '2', name: 'Zone Racines', type: 'culture', shape: 'rect', x: 2, y: 4, width: 4, height: 2, rotation: 0, opacity: 1, exposure: 'Soleil', plantedCultureId: 'pdt', selectedVariety: 'Charlotte' },
  { id: '3', name: 'Grand Chêne', type: 'tree', shape: 'circle', x: 10, y: 2, width: 3, height: 3, rotation: 0, opacity: 0.8, exposure: 'Soleil' },
  { id: '4', name: 'Abri de jardin', type: 'building', shape: 'rect', x: 12, y: 7, width: 2, height: 2, rotation: 15, opacity: 1, exposure: 'Ombre' },
  { id: '5', name: 'Citerne Pluie', type: 'water_tank', shape: 'circle', x: 13, y: 6, width: 1, height: 1, rotation: 0, opacity: 1, exposure: 'Ombre' }
];
// API Backend (Vite env)
export const API_URL = import.meta.env.VITE_API_URL as string;